build_folder_patterns:
  - "^builds_ns(/.*)?/build_[a-z0-9_]+_a$"
  - "^builds_ns(/.*)?/build_.*_[0-9]{4}$"
  - "^builds_ns(/.*)?/build.*_[a-z0-9]{11}$"
# Protected paths (do not delete or cold-store these)
protected_paths:
  - "build_tools/"
  - "builds_ns/builds_xs/"
  - "builds_ns/ns1/"

# Time threshold in days (default: 730 days = 2 years)
time_threshold_days: 300

# List of custom cleanup target paths (add your paths here)
cleanup_target_paths:
  - "builds_ns/builds_zion/gcov/"

log_level: INFO

# Artifactory connection and AQL pagination parameters
# (Set only one of username/password or access_token)
artifactory_url: "https://<artifactory_url>/artifactory"
username: ""
password: ""
access_token: ""
aql_limit: 10000

# Chunk size for splitting deletion tasks
chunk_size: 100
